/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tk2_kelompok7;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author macproi52019
 */
public class frameDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameDashboard.class.getName());

    /**
     * Creates new form frameDashboard
     */
    public frameDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        bCocacola = new javax.swing.JButton();
        bTehpucuk = new javax.swing.JButton();
        bGolda = new javax.swing.JButton();
        bSprite = new javax.swing.JButton();
        bPepsi = new javax.swing.JButton();
        bFanta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelSidebar.setBackground(new java.awt.Color(230, 202, 173));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel1.setText(" Dashboard ");

        bBack.setBackground(new java.awt.Color(230, 202, 173));
        bBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok7/icon/icons8-close-20 (2).png"))); // NOI18N
        bBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBackMouseClicked(evt);
            }
        });
        bBack.addActionListener(this::bBackActionPerformed);

        jLabel4.setText("Menu Navigasi From Mahasiswa | Pemrograman Berorientasi Objek | Kelompok 7");

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Minuman");
        jLabel2.setPreferredSize(new java.awt.Dimension(139, 25));

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(153, Short.MAX_VALUE))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bBack)
                        .addGap(15, 15, 15))))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bBack))
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.PAGE_START);

        panelContent.setBackground(new java.awt.Color(233, 220, 179));

        bCocacola.setBackground(new java.awt.Color(230, 202, 173));
        bCocacola.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        bCocacola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok7/icon/icons8-coca-cola-50.png"))); // NOI18N
        bCocacola.setText("Coca-Cola");
        bCocacola.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCocacola.addActionListener(this::bCocacolaActionPerformed);

        bTehpucuk.setBackground(new java.awt.Color(230, 202, 173));
        bTehpucuk.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        bTehpucuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok7/icon/icons8-drink-50.png"))); // NOI18N
        bTehpucuk.setText("Teh Pucuk");
        bTehpucuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bTehpucuk.addActionListener(this::bTehpucukActionPerformed);

        bGolda.setBackground(new java.awt.Color(230, 202, 173));
        bGolda.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        bGolda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok7/icon/icons8-coffee-to-go-50.png"))); // NOI18N
        bGolda.setText("Golda Coffe");
        bGolda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bGolda.addActionListener(this::bGoldaActionPerformed);

        bSprite.setBackground(new java.awt.Color(230, 202, 173));
        bSprite.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        bSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok7/icon/icons8-can-50 (1).png"))); // NOI18N
        bSprite.setText("Sprite");
        bSprite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bSprite.addActionListener(this::bSpriteActionPerformed);

        bPepsi.setBackground(new java.awt.Color(230, 202, 173));
        bPepsi.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        bPepsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok7/icon/icons8-can-50 (2).png"))); // NOI18N
        bPepsi.setText("Pepsi");
        bPepsi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bPepsi.addActionListener(this::bPepsiActionPerformed);

        bFanta.setBackground(new java.awt.Color(230, 202, 173));
        bFanta.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        bFanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_kelompok7/icon/icons8-can-50.png"))); // NOI18N
        bFanta.setText("Fanta");
        bFanta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bFanta.addActionListener(this::bFantaActionPerformed);

        jLabel3.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 12)); // NOI18N
        jLabel3.setText("Praktikum PBO - Kelompok 7 • Institut Teknologi Mojosari ");

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bCocacola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bGolda, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(bFanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bTehpucuk, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(bSprite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bPepsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bCocacola, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(bTehpucuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bGolda, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(bPepsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bFanta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBackActionPerformed

    private void bCocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCocacolaActionPerformed
        // TODO add your handling code here:
        frameCocacola frame = new frameCocacola();
        frame.setVisible(true);
        dispose();

    }//GEN-LAST:event_bCocacolaActionPerformed

    private void bBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBackMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bBackMouseClicked

    private void bFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFantaActionPerformed
        // TODO add your handling code here:
         frameFanta frame = new frameFanta();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_bFantaActionPerformed

    private void bGoldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGoldaActionPerformed
        // TODO add your handling code here:
        frameGoldacoffee frame = new frameGoldacoffee();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_bGoldaActionPerformed

    private void bTehpucukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTehpucukActionPerformed
        // TODO add your handling code here:
        frameTehPucuk frame = new frameTehPucuk();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_bTehpucukActionPerformed

    private void bSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSpriteActionPerformed
        // TODO add your handling code here:
         FrameSprite frame = new FrameSprite();
        frame.setVisible(true);
        dispose();    
    }//GEN-LAST:event_bSpriteActionPerformed

    private void bPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPepsiActionPerformed
        // TODO add your handling code here:
        framePepsi frame = new framePepsi();
        frame.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_bPepsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            UIManager.put("Button.arc", 15);
            UIManager.put("TextComponent.arc", 15);
            UIManager.put("Button.borderWidth", 0);
            UIManager.put("Component.borderWidth", 0);
            UIManager.put("Component.focusWidth", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bCocacola;
    private javax.swing.JButton bFanta;
    private javax.swing.JButton bGolda;
    private javax.swing.JButton bPepsi;
    private javax.swing.JButton bSprite;
    private javax.swing.JButton bTehpucuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
